// import {Country,State,City}  from 'country-state-city';  



export const ageDiff = [
  { value: 18 },
  { value: 19 },
  { value: 20 },
  { value: 21 },
  { value: 22 },
  { value: 23 },
  { value: 24 },
  { value: 25 },
  { value: 0 },
  { value: 1 },
  { value: 2 },
  { value: 4 },
  { value: 0 },
  { value: 1 },
  { value: 2 },
  { value: 4 },
  { value: 0 },
  { value: 1 },
  { value: 2 },
  { value: 4 },
  { value: 0 },
  { value: 1 },
  { value: 2 },
  { value: 4 },
];



export const familyValbro = [
  { title: "0" },
  { title: "1" },
  { title: "2" },
  { title: "3" },
];



// no of sister
export const familyValsis = [
  { title: "0" },
  { title: "1" },
  { title: "2" },
  { title: "3" },
];

export const profileoption = [
    { title: "Self" },
    { title: "Son" },
    { title: "Daughter" },
    { title: "Brother" },
    { title: "Sister" },
    { title: "Other" },
  ];
  export const religionoption = [
    { title: "Hindu" },
    { title: "Muslim" },
    { title: "Christian" },
    { title: "Sikh" },
    { title: "Buddhist" },
    { title: "Jain" },
    { title: "Other Religions" },
  ];
  // chidoption
  export const chidoption = [
    { title: "0",key:0 },
    { title: "1" ,key:1},
    { title: "2" ,key:2},
    { title: "3" ,key:3},
    { title: "4" ,key:4},
  ];
  // languageoption
  export const languageoption = [
    { title: "Hindi" ,key:1},
    { title: "Gujarati" ,key:2},
    { title: "Marathi" ,key:3},
    { title: "Punjabi" ,key:4},
    { title: "Konkani" ,key:5},
    { title: "English" ,key:6},
    { title: "Halabi" ,key:7},
  ];
  export const statusoption = [
    { value: "SINGLE" ,title:"Single"},
    { value: "DIVORCED" ,title:"Divorce"},
    { value: "AWAITING_DIVORCE" ,title:"Awaiting Divorce"},
    { value: "WIDOW",title:"Widow" },
    { value: "ANY",title:"Any" },
    { value: "NOT_SPECIFIED" ,title:"Not Specified"},
  ];
  
  export const annualoption = [
    { title: "Not Working" ,value:0},
    { title: "Upto INR 1 Lakh" ,value:1},
    { title: "INR 1 Lakh to 2 Lakh" ,value:2},
    { title: "INR 2 Lakh to 4 Lakh" ,value:3},
    { title: "INR 4 Lakh to 7 Lakh" ,value:4},
    { title: "INR 7 Lakh to 10 Lakh",value:5 },
    { title: "INR 10 Lakh to 15 Lakh" ,value:6},
    { title: "INR 15 Lakh to 20 Lakh" ,value:7},
    { title: "INR 20 Lakh to 30 Lakh",value:8 },
    { title: "INR 30 Lakh to 50 Lakh" ,value:9},
    { title: "INR 50 Lakh to 90 Lakh" ,value:10},
    { title: "Above 90 Lakh" ,value:11},
  ];
  export const familyVal = [
    { value: "ORTHODOX" ,title:"Orthodox"},
    { value: "TRADITIONAL",title:"Traditional" },
    { value: "MODERATE" ,title:"Moderate"},
    { value: "LIBERAL" ,title:"Liberal"},
  ];
  export const heightoption = [
    { title: "4 ft 0 in" ,value:0},
    { title: "4 ft 1 in" ,value:1},
    { title: "4 ft 2 in" ,value:2},
    { title: "4 ft 3 in" ,value:3},
    { title: "4 ft 4 in" ,value:4},
    { title: "4 ft 5 in" ,value:5},
    { title: "4 ft 6 in" ,value:6},
    { title: "4 ft 7 in" ,value:7},
    { title: "4 ft 8 in" ,value:8},
    { title: "4 ft 9 in" ,value:9},
    { title: "4 ft 10 in" ,value:10},
    { title: "4 ft 11 in" ,value:11},
    { title: "5 ft 0 in	" ,value:12},
    { title: "5 ft 1 in" ,value:13},
    { title: "5 ft 2 in" ,value:14},
    { title: "5 ft 3 in" ,value:15},
    { title: "5 ft 4 in" ,value:16},
    { title: "5 ft 5 in" ,value:17},
    { title: "5 ft 6 in" ,value:18},
    { title: "5 ft 7 in" ,value:19},
    { title: "5 ft 8 in" ,value:20},
    { title: "5 ft 9 in" ,value:21},
    { title: "5 ft 10 in" ,value:22},
    { title: "5 ft 11 in" ,value:23},
    { title: "Not Specified" ,value:24},
    
  ];
  // Loction
  export const countryoption = [
    { title: "India" },
    { title: "China" },
    { title: "Germany" },
    { title: "Italy" },
  
    { title: "America" },
  ];

  export const citizenshipoption = [
    { title: "India" },
    { title: "China" },
    { title: "Germany" },
    { title: "Italy" },
  
    { title: "America" },
  ];

  export const raashi =[
    'Aries',
    'Taurus',
    'Gemini',
    'Cancer',
    'Leo',
    'Virgo',
    'Libra',
    'Scorpio',
    'Sagittarius',
    'Capricorn',
    'Aquarius',
    'Pisces',

  ]
  export const stateoption = [
    { title: "Bihar" },
    { title: "Gujarat" },
    { title: "Karnataka" },
    { title: "Maharashtra" },
    { title: "Orissa" },
    { title: "Rajasthan" },
    { title: "Punjab" },
  ];
  export const cityoption = [
    { title: "Mumbai" },
    { title: "Pune" },
    { title: "Hydrabad" },
    { title: "Nagpur" },
  ];
  export const motherTongue=[{ title: "Aka" },
  { title: "Arabic" },
  { title: "Arunachali" },
  { title: "Assamese" },
  { title: "Awadhi" },
  { title: "Baluchi" },
  { title: "Bengali" },
  { title: "Bhojpuri" },
  { title: "Bhutia" },
  { title: "Brahui" },
  { title: "Brij" },
  { title: "Burmese" },
  { title: "Chattisgarhi" },
  { title: "Chinese" },
  { title: "Coorgi" },
  { title: "Dogri" },
  { title: "English" },
  { title: "French" },
  { title: "Garhwali" },
  { title: "Garo" },
  { title: "Gujarati" },
  { title: "Haryanavi" },
  { title: "Himachali/Pahari" },
  { title: "Hindi" },
  { title: "Hindko" },
  { title: "Kakbarak" },
  { title: "Kanauji" },
  { title: "Kannada" },
  { title: "Kashmiri" },
  { title: "Khandesi" },
  { title: "Khasi" },
  { title: "Konkani" },
  { title: "Koshali" },
  { title: "Kumaoni" },
  { title: "Kutchi" },
  { title: "Ladakhi" },
  { title: "Lepcha" },
  { title: "Magahi" },
  { title: "Maithili" },
  { title: "Malay" },
  { title: "Malayalam" },
  { title: "Manipuri" },
  { title: "Marathi" },
  { title: "Marwari" },
  { title: "Miji" },
  { title: "Mizo" },
  { title: "Monpa" },
  { title: "Nepali" },
  { title: "Odia" },
  { title: "Pashto" },
  { title: "Persian" },
  { title: "Punjabi" },
  { title: "Rajasthani" },
  { title: "Russian" },
  { title: "Sanskrit" },
  { title: "Santhali" },
  { title: "Seraiki" },
  { title: "Sindhi" },
  { title: "Sinhala" },
  { title: "Sourashtra" },
  { title: "Spanish" },
  { title: "Swedish" },
  { title: "Tagalog" },
  { title: "Tamil" },
  { title: "Telugu" },
  { title: "Tulu" },
  { title: "Urdu" },
  { title: "Other" },
]
  export const rassioption = [
        { title: "Aries" },
        { title: "Gemini" },
        { title: "Cancer" },
        { title: "Leo" },
        { title: "Virgo" },
        { title: "Taurus" },
        { title: "Libra" },
        { title: "Scorpio" },
        { title: "Sagittarius" },
        { title: "Capricorn" },
        { title: "Aquarius" },
        { title: "Pisces" },
    
  ];
  export const castoption = [
    { title: "24 Manai Telugu Chettiar" },
    { title: "96 Kuli Maratha" },
    { title: "96K Kokanastha" },
    { title: "Adi Andhra" },
    { title: "Adi Dharmi" },
    { title: "Adi Dravida" },
    { title: "Adi Karnataka" },
    { title: "Agamudayar" },
    { title: "Agarwal" },
    { title: "Agnikula Kshatriya" },
    { title: "Agri" },
    { title: "Ahir" },
    { title: "Ahom" },
    { title: "Ambalavasi" },
    { title: "Arcot" },
    { title: "Arekatica" },
    { title: "Arora" },
    { title: "Arunthathiyar" },
    { title: "Arya Vysya" },
    { title: "Aryasamaj" },
    { title: "Ayyaraka" },
    { title: "Badaga" },
    { title: "Baghel/Pal/Gaderiya" },
    { title: "Bahi" },
    { title: "Baidya" },
    { title: "Baishnab" },
    { title: "Baishya" },
    { title: "Bajantri" },
    { title: "Balija" },
    { title: "Balija - Naidu" },
    { title: "Banayat Oriya" },
    { title: "Banik" },
    { title: "Baniya" },
    { title: "Barai" },
    { title: "Bari" },
    { title: "Barnwal" },
    { title: "Barujibi" },
    { title: "Bengali" },
    { title: "Besta" },
    { title: "Bhandari" },
    { title: "Bhatia" },
    { title: "Bhatraju" },
    { title: "Bhavsar" },
    { title: "Bhovi" },
    { title: "Billava" },
    { title: "Boya/Nayak/Naik" },
    { title: "Boyer" },
    { title: "Brahmbatt" },
    { title: "Brahmin" },
    { title: "Brahmin - Anavil" },
    { title: "Brahmin - Audichya" },
    { title: "Brahmin - Barendra" },
    { title: "Brahmin - Bengali" },
    { title: "Brahmin - Bhatt" },
    { title: "Brahmin - Bhumihar" },
    { title: "Brahmin - Brahmbhatt" },
    { title: "Brahmin - Dadhich/Dadheech" },
    { title: "Brahmin - Daivadnya" },
    { title: "Brahmin - Danua" },
    { title: "Brahmin - Deshastha" },
    { title: "Brahmin - Dhiman" },
    { title: "Brahmin - Dravida" },
    { title: "Brahmin - Embrandiri" },
    { title: "Brahmin - Garhwali" },
    { title: "Brahmin - Goswami" },
    { title: "Brahmin - Gour" },
    { title: "Brahmin - Gowd Saraswat" },
    { title: "Brahmin - Gujar Gour" },
    { title: "Brahmin - Gurukkal" },
    { title: "Brahmin - Halua" },
    { title: "Brahmin - Havyaka" },
    { title: "Brahmin - Himachali" },
    { title: "Brahmin - Hoysala" },
    { title: "Brahmin - Iyengar" },
    { title: "Brahmin - Iyer" },
    { title: "Brahmin - Jangid" },
    { title: "Brahmin - Jhadua" },
    { title: "Brahmin - Jhijhotiya" },
    { title: "Brahmin - Kannada Madhva" },
    { title: "Brahmin - Kanyakubja" },
    { title: "Brahmin - Karhade" },
    { title: "Brahmin - Kashmiri Pandit" },
    { title: "Brahmin - Kokanastha" },
    { title: "Brahmin - Kota" },
    { title: "Brahmin - Kulin" },
    { title: "Brahmin - Kumaoni" },
    { title: "Brahmin - Madhwa" },
    { title: "Brahmin - Maharashtrian" },
    { title: "Brahmin - Maithili" },
    { title: "Brahmin - Modh" },
    { title: "Brahmin - Mohyal" },
    { title: "Brahmin - Nagar" },
    { title: "Brahmin - Namboodiri" },
    { title: "Brahmin - Niyogi" },
    { title: "Brahmin - Niyogi Nandavariki" },
    { title: "Brahmin - Other" },
    { title: "Brahmin - Paliwal" },
    { title: "Brahmin - Panda" },
    { title: "Brahmin - Pareek" },
    { title: "Brahmin - Punjabi" },
    { title: "Brahmin - Pushkarna" },
    { title: "Brahmin - Rarhi" },
    { title: "Brahmin - Rudraj" },
    { title: "Brahmin - Sakaldwipi" },
    { title: "Brahmin - Sanadya" },
    { title: "Brahmin - Sanketi" },
    { title: "Brahmin - Saraswat" },
    { title: "Brahmin - Sarua" },
    { title: "Brahmin - Saryuparin" },
    { title: "Brahmin - Shivhalli" },
    { title: "Brahmin - Shrimali" },
    { title: "Brahmin - Smartha" },
    { title: "Brahmin - Sri Vaishnava" },
    { title: "Brahmin - Stanika" },
    { title: "Brahmin - Tyagi" },
    { title: "Brahmin - Vaidiki" },
    { title: "Brahmin - Vaikhanasa" },
    { title: "Brahmin - Velanadu" },
    { title: "Brahmin - Viswabrahmin" },
    { title: "Brahmin - Vyas" },
    { title: "Brahmo" },
    { title: "Buddar" },
    { title: "Bunt (Shetty)" },
    { title: "CKP" },
    { title: "Chalawadi Holeya" },
    { title: "Chambhar" },
    { title: "Chandravanshi Kahar" },
    { title: "Chasa" },
    { title: "Chattada Sri Vaishnava" },
    { title: "Chaudary" },
    { title: "Chaurasia" },
    { title: "Chekkala - Nair" },
    { title: "Chennadasar" },
    { title: "Cheramar" },
    { title: "Chettiar" },
    { title: "Chhetri" },
    { title: "Chippolu/Mera" },
    { title: "Coorgi" },
    { title: "Devadiga" },
    { title: "Devanga" },
    { title: "Devar/Thevar/Mukkulathor" },
    { title: "Devendra Kula Vellalar" },
    { title: "Dhangar" },
    { title: "Dheevara" },
    { title: "Dhiman" },
    { title: "Dhoba" },
    { title: "Dhobi" },
    { title: "Digambar" },
    { title: "Dommala" },
    { title: "Dusadh" },
    { title: "Ediga" },
    { title: "Ezhava" },
    { title: "Ezhuthachan" },
    { title: "Gabit" },
    { title: "Ganakar" },
    { title: "Gandla" },
    { title: "Ganiga" },
    { title: "Garhwali" },
    { title: "Gatti" },
    { title: "Gavali" },
    { title: "Gavara" },
    { title: "Ghumar" },
    { title: "Goala" },
    { title: "Goan" },
    { title: "Goswami" },
    { title: "Goud" },
    { title: "Gounder" },
    { title: "Gowda" },
    { title: "Gramani" },
    { title: "Gudia" },
    { title: "Gujarati" },
    { title: "Gujjar" },
    { title: "Gupta" },
    { title: "Guptan" },
    { title: "Gurjar" },
    { title: "Halwai" },
    { title: "Hegde" },
    { title: "Helava" },
    { title: "Hugar (Jeer)" },
    { title: "Intercaste" },
    { title: "Jaalari" },
    { title: "Jaiswal" },
    { title: "Jandra" },
    { title: "Jangam" },
    { title: "Jat" },
    { title: "Jatav" },
    { title: "Jetty Malla" },
    { title: "Kachara" },
    { title: "Kaibarta" },
    { title: "Kakkalan" },
    { title: "Kalar" },
    { title: "Kalinga" },
    { title: "Kalinga Vysya" },
    { title: "Kalita" },
    { title: "Kalwar" },
    { title: "Kamboj" },
    { title: "Kamma" },
    { title: "Kamma Naidu" },
    { title: "Kammala" },
    { title: "Kaniyan" },
    { title: "Kannada Mogaveera" },
    { title: "Kansari" },
    { title: "Kanu" },
    { title: "Kapu" },
    { title: "Kapu Naidu" },
    { title: "Karana" },
    { title: "Karmakar" },
    { title: "Kartha" },
    { title: "Karuneegar" },
    { title: "Kasar" },
    { title: "Kashyap" },
    { title: "Kavuthiyya/Ezhavathy" },
    { title: "Kayastha" },
    { title: "Khandayat" },
    { title: "Khandelwal" },
    { title: "Kharwar" },
    { title: "Khatik" },
    { title: "Khatri" },
    { title: "Kirar" },
    { title: "Koli" },
    { title: "Koli Patel" },
    { title: "Kongu Vellala Gounder" },
    { title: "Konkani" },
    { title: "Korama" },
    { title: "Kori" },
    { title: "Koshti" },
    { title: "Krishnavaka" },
    { title: "Kshatriya" },
    { title: "Kshatriya - Bhavasar" },
    { title: "Kshatriya/Raju/Varma" },
    { title: "Kudumbi" },
    { title: "Kulal" },
    { title: "Kulalar" },
    { title: "Kulita" },
    { title: "Kumawat" },
    { title: "Kumbara" },
    { title: "Kumbhakar/Kumbhar" },
    { title: "Kumhar" },
    { title: "Kummari" },
    { title: "Kunbi" },
    { title: "Kurava" },
    { title: "Kuravan" },
    { title: "Kurmi" },
    { title: "Kurmi Kshatriya" },
    { title: "Kuruba" },
    { title: "Kuruhina Shetty" },
    { title: "Kurumbar" },
    { title: "Kurup" },
    { title: "Kushwaha" },
    { title: "Kutchi" },
    { title: "Lambadi/Banjara" },
    { title: "Lambani" },
    { title: "Leva Patil" },
    { title: "Lingayath" },
    { title: "Lohana" },
    { title: "Lohar" },
    { title: "Loniya/Lonia/Lunia" },
    { title: "Lubana" },
    { title: "Madhesiya" },
    { title: "Madiga" },
    { title: "Mahajan" },
    { title: "Mahar" },
    { title: "Maharashtrian" },
    { title: "Mahendra" },
    { title: "Maheshwari" },
    { title: "Mahindra" },
    { title: "Mahishya" },
    { title: "Majabi" },
    { title: "Mala" },
    { title: "Malayalee Variar" },
    { title: "Mali" },
    { title: "Mallah" },
    { title: "Mangalorean" },
    { title: "Maniyani" },
    { title: "Mannadiar" },
    { title: "Mannan" },
    { title: "Mapila" },
    { title: "Marar" },
    { title: "Maratha" },
    { title: "Maratha - Gomantak" },
    { title: "Maruthuvar" },
    { title: "Marvar" },
    { title: "Marwari" },
    { title: "Matang" },
    { title: "Maurya" },
    { title: "Meda" },
    { title: "Medara" },
    { title: "Meena" },
    { title: "Meenavar" },
    { title: "Meghwal" },
    { title: "Mehra" },
    { title: "Menon" },
    { title: "Meru Darji" },
    { title: "Modak" },
    { title: "Mogaveera" },
    { title: "Monchi" },
    { title: "Mudaliar" },
    { title: "Mudaliar - Arcot" },
    { title: "Mudaliar - Saiva" },
    { title: "Mudaliar - Senguntha" },
    { title: "Mudiraj" },
    { title: "Munnuru Kapu" },
    { title: "Muthuraja" },
    { title: "Naagavamsam" },
    { title: "Nadar" },
    { title: "Nagaralu" },
    { title: "Nai" },
    { title: "Naicken" },
    { title: "Naicker" },
    { title: "Naidu" },
    { title: "Naik" },
    { title: "Nair" },
    { title: "Nair - Vaniya" },
    { title: "Nair - Velethadathu" },
    { title: "Nair - Vilakkithala" },
    { title: "Namasudra" },
    { title: "Nambiar" },
    { title: "Nambisan" },
    { title: "Namdev" },
    { title: "Namosudra" },
    { title: "Napit" },
    { title: "Nayak" },
    { title: "Nayaka" },
    { title: "Neeli" },
    { title: "Nepali" },
    { title: "Nhavi" },
    { title: "OBC - Barber/Naayee" },
    { title: "Oswal" },
    { title: "Otari" },
    { title: "Padmasali" },
    { title: "Panchal" },
    { title: "Pandaram" },
    { title: "Panicker" },
    { title: "Paravan" },
    { title: "Parit" },
    { title: "Parkava Kulam" },
    { title: "Partraj" },
    { title: "Pasi" },
    { title: "Paswan" },
    { title: "Patel" },
    { title: "Patel - Desai" },
    { title: "Patel - Dodia" },
    { title: "Patel - Kadva" },
    { title: "Patel - Leva" },
    { title: "Patnaick" },
    { title: "Patra" },
    { title: "Patwa" },
    { title: "Perika" },
    { title: "Pillai" },
    { title: "Pisharody" },
    { title: "Poduval" },
    { title: "Poosala" },
    { title: "Porwal" },
    { title: "Prajapati" },
    { title: "Pulaya" },
    { title: "Punjabi" },
    { title: "Raigar" },
    { title: "Rajaka" },
    { title: "Rajaka/Chakali/Dhobi" },
    { title: "Rajbhar" },
    { title: "Rajput" },
    { title: "Rajput - Garhwali" },
    { title: "Rajput - Kumaoni" },
    { title: "Rajput - Lodhi" },
    { title: "Ramdasia" },
    { title: "Ramgharia" },
    { title: "Rauniyar" },
    { title: "Ravidasia" },
    { title: "Rawat" },
    { title: "Reddiar" },
    { title: "Reddy" },
    { title: "Relli" },
    { title: "SSK" },
    { title: "Sadgop" },
    { title: "Sagara - Uppara" },
    { title: "Saha" },
    { title: "Sahu" },
    { title: "Saini" },
    { title: "Saiva Vellala" },
    { title: "Saliya" },
    { title: "Sambava" },
    { title: "Satnami" },
    { title: "Savji" },
    { title: "Scheduled Caste (SC)" },
    { title: "Scheduled Tribe (ST)" },
    { title: "Senai Thalaivar" },
    { title: "Sepahia" },
    { title: "Setti Balija" },
    { title: "Shah" },
    { title: "Shilpkar" },
    { title: "Shimpi" },
    { title: "Sindhi" },
    { title: "Sindhi - Bhanusali" },
    { title: "Sindhi - Bhatia" },
    { title: "Sindhi - Chhapru" },
    { title: "Sindhi - Dadu" },
    { title: "Sindhi - Hyderabadi" },
    { title: "Sindhi - Larai" },
    { title: "Sindhi - Lohana" },
    { title: "Sindhi - Rohiri" },
    { title: "Sindhi - Sehwani" },
    { title: "Sindhi - Thatai" },
    { title: "Sindhi-Amil" },
    { title: "Sindhi-Baibhand" },
    { title: "Sindhi-Larkana" },
    { title: "Sindhi-Sahiti" },
    { title: "Sindhi-Sakkhar" },
    { title: "Sindhi-Shikarpuri" },
    { title: "Somvanshi" },
    { title: "Sonar" },
    { title: "Soni" },
    { title: "Sourashtra" },
    { title: "Sowrashtra" },
    { title: "Sozhiya Vellalar" },
    { title: "Sri Vaishnava" },
    { title: "Srisayana" },
    { title: "Subarna Banik" },
    { title: "Sugali (Naika)" },
    { title: "Sundhi" },
    { title: "Surya Balija" },
    { title: "Sutar" },
    { title: "Suthar" },
    { title: "Swakula Sali" },
    { title: "Swarnakar" },
    { title: "Tamboli" },
    { title: "Tamil Yadava" },
    { title: "Tanti" },
    { title: "Tantuway" },
    { title: "Telaga" },
    { title: "Teli" },
    { title: "Telugu" },
    { title: "Thachar" },
    { title: "Thakkar" },
    { title: "Thakur" },
    { title: "Thandan" },
    { title: "Thigala" },
    { title: "Thiyya" },
    { title: "Thuluva Vellala" },
    { title: "Tili" },
    { title: "Togata" },
    { title: "Turupu Kapu" },
    { title: "Udayar" },
    { title: "Urali Gounder" },
    { title: "Urs" },
    { title: "Vada Balija" },
    { title: "Vadagalai" },
    { title: "Vaddera" },
    { title: "Vaduka" },
    { title: "Vaish" },
    { title: "Vaish - Dhaneshawat" },
    { title: "Vaishnav" },
    { title: "Vaishnav - Bhatia" },
    { title: "Vaishnav - Vania" },
    { title: "Vaishya" },
    { title: "Vallala" },
    { title: "Valluvan" },
    { title: "Valmiki" },
    { title: "Vanika Vyshya" },
    { title: "Vaniya Chettiar" },
    { title: "Vanjara" },
    { title: "Vankar" },
    { title: "Vannan" },
    { title: "Vannar" },
    { title: "Vanniyakullak Kshatriya" },
    { title: "Vanniyar" },
    { title: "Variar" },
    { title: "Varshney" },
    { title: "Veera Saivam" },
    { title: "Veerashaiva" },
    { title: "Velaan" },
    { title: "Velama" },
    { title: "Velar" },
    { title: "Vellalar" },
    { title: "Veluthedathu - Nair" },
    { title: "Vettuva Gounder" },
    { title: "Vishwakarma" },
    { title: "Viswabrahmin" },
    { title: "Vokaliga" },
    { title: "Vokkaliga" },
    { title: "Vysya" },
    { title: "Waada Balija" },
    { title: "Yadav" },
    { title: "Yellapu" },
    { title: "Other" },
  ];
  export const degreeoption = [
    { title: "BE" },
    { title: "MCA" },
    { title: "MSC" },
    { title: "BSC" },
  ];
  export const employoption = [
    { title: "Self Employed" ,value:"SELFEMPLOYED"},
    { title: "Government" ,value:"GOVERNMENT"},
    { title: "Private" ,value:"PRIVATE"},
    { title: "Bussiness" ,value:"BUSINESS"},
    { title: "Defence" ,value:"DEFENCE"},
    { title: "Not-working" ,value:"NOTWORKING"},
    { title: "Other" ,value:"OTHER"},
  ];
  export const employeeption = [
    { title: "IT" },
    { title: "Marketing" },
    { title: "Bank" },
    { title: "other" },
  ];

  export const familyType = [
    { title: "Joint Family" ,value:'JOINT_FAMILY'},
    { title: "Nuclear Family" ,value:'NUCLEAR_FAMILY'}
  ];


export const familyStatus=[
  { title: "Middle Class" ,value:'MIDDLE_CLASS'},
  { title: "Upper Middle Class" ,value:'UPPER_MIDDLE_CLASS'},
  { title: "Rich Affluent" ,value:'RICH_AFFLUENT'},
]

export const education_=[
  "B.E / B.Tech",
  "M.E / M.Tech",
  "M.S Engineering",
  "B.Eng (Hons)",
  "M.Eng (Hons)",
  "Engineering Diploma",
  "AE",
  "AET",
  "B.A",
  "B.Ed",
  "BJMC",
  "BFA",
  "B.Arch",
  "B.Des",
  "BMM",
  "MFA",
  "M.Ed",
  "M.A",
  "MSW",
  "MJMC",
  "M.Arch",
  "M.Des",
  "BA (Hons)",
  "B.Arch (Hons)",
  "DFA",
  "D.Ed",
  "D.Arch",
  "AA",
  "AFA",
  "B.Com",
  "CA / CPA",
  "CFA",
  "CS",
  "BSc / BFin",
  "M.Com",
  "MSc / MFin / MS",
  "BCom (Hons)",
  "PGD Finance",
  "BCA",
  "B.IT",
  "BCS",
  "BA Computer Science",
  "MCA",
  "PGDCA",
  "IT Diploma",
  "ADIT",
  "B.Sc",
  "M.Sc",
  "BSc (Hons)",
  "DipSc",
  "AS",
  "AAS",
  "MBBS",
  "BDS",
  "BPT",
  "BAMS",
  "BHMS",
  "B.Pharma",
  "BVSc",
  "BSN / BScN",
  "MDS",
  "MCh",
  "M.D",
  "M.S Medicine",
  "MPT",
  "DM",
  "M.Pharma",
  "MVSc",
  "MMed",
  "PGD Medicine",
  "ADN",
  "BBA",
  "BHM",
  "BBM",
  "MBA",
  "PGDM",
  "ABA",
  "ADBus",
  "BL / LLB",
  "ML / LLM",
  "LLB (Hons)",
  "ALA",
  "Ph.D",
  "M.Phil",
  "Bachelor",
  "Master",
  "Diploma",
  "Honours",
  "Doctorate",
  "Associate",
  "High school",
  "Less than high school",
]

export const hobbies=[
    "Acting",
  'Animal breeding',
  'Art / Handicraft',
  'Astrology / Palmistry / Numerology',
  'Astronomy',
  'Bird watching',
  'Collectibles',
  'Cooking',
  'Dancing',
  'DIY(do it yourself) projects',
  'Film-making','Fishing',
  'Gardening / Landscaping',
  'Graphology',
  'Ham radio',
  'Home / Interior decoration',
   'Hunting',  
   'Model building',
   'Painting / Drawing',
   'Photography',
   'Playing musical instruments',
   'Singing',
   'Solving Crosswords', 'Puzzles'
  // Will tell you later
]


 export const gotram=[
  "Aatharvas",
  "Agasthi",
  "Ahabhunasa",
  "Airan",
  "Alampayana",
  "Angiras",
  "Arrishinimi",
  "Athreyasya/ Athreyasa",
  "Atri",
  "Attarishi",
  "Aukshanas",
  "Aushanas",
  "Babrahvya",
  "Badarayana",
  "Baijvayas",
  "Bansal",
  "Bashan",
  "Bhandal",
  "Bharadwaj",
  "Bhargava / Bhargav",
  "Bhasyan",
  "Bhrigu",
  "Bindal",
  "Birthare",
  "Bodhaaynas",
  "Chandratri",
  "Chikithasa",
  "Chyavanasa",
  "Daksa",
  "Dalabhya",
  "Darbhas",
  "Devrata",
  "Dhananjaya",
  "Dhanvantri",
  "Dhara Gautam",
  "Dharan",
  "Dharanas",
  "Dixit",
  "Duttatreyas",
  "Galiva",
  "Ganganas",
  "Gangyanas",
  "Gardhmukh Sandilya",
  "Garg",
  "Garga / Gargya",
  "Gargya Sainasa",
  "Gautam / Gouthama",
  "Ghrit Kaushika",
  "Gowri Veetham",
  "Goyal",
  "Goyan",
  "Haritasya / Harithasa / Haritha",
  "Jaiminiyas",
  "Jamadagni",
  "Jatukarna",
  "Jindal",
  "Kaakavas",
  "Kabi",
  "Kalabouddasa",
  "Kalpangeerasa",
  "Kamakayana Vishwamitra",
  "Kamsa",
  "Kanav",
  "Kansal",
  "Kanva",
  "Kapi",
  "Kapila",
  "Kapinjal",
  "Kapishthalas",
  "Kaplish Baradwaj",
  "Kashish",
  "Kashyapa / Kaashyapa",
  "Katyayan / Katyan",
  "Kaundinya / Koundanya / Kaundilya",
  "Kaunsa",
  "Kaushal",
  "Kaushika / Kaushik / Kausikasa",
  "Keshoryas",
  "Koushika Visvamitrasa",
  "Krishnatrey",
  "Kucchal",
  "Kusa",
  "Kutsa / Kutsas / Kutsasa",
  "Laakshmanas",
  "Laugakshi",
  "Lavania",
  "Lodwan",
  "Lohit",
  "Lokaakhyas",
  "Lomasha",
  "Madelia",
  "Madhukul",
  "Maitraya",
  "Manava",
  "Mandavya",
  "Mangal",
  "Marica",
  "Markendeya",
  "Maudlas",
  "Maunas",
  "Mihir",
  "Mittal",
  "Moudgalya",
  "Mouna Bhargava",
  "Munish",
  "Mythravaruna",
  "Naagal",
  "Nagasya",
  "Naidrupa Kashyapa",
  "Narayanas",
  "Nithyandala",
  "Paaniyas",
  "Pachori",
  "Paing",
  "Parashar / Parashara",
  "Parthivasa",
  "Paulastya",
  "Poothamanasa",
  "Pourugutsa",
  "Prachinas",
  "Raghuvanshi",
  "Rajoria",
  "Rathitar",
  "Rohinya",
  "Rohita",
  "Sakalya",
  "Sakhyanasa",
  "Salankayanasa",
  "Sankash",
  "Sankha",
  "Sankrut",
  "Sankyanasa",
  "Savanaka",
  "Savarana / Sabarna / Savarna / Sraborno",
  "Shaalaksha",
  "Shadamarshana / Shatamarshanam",
  "Shakhanas",
  "Shalavatsa",
  "Shandilya / Sandilyasa",
  "Sharkaras",
  "Sharkvas",
  "Shaunak",
  "Shravanesya",
  "Shrimukh  Shandilya",
  "Shukla Atreyas",
  "Sigidha",
  "Singhal",
  "Sri Vatsa / Vatsa / Vats / Vacchas",
  "Srungi Bharadwajasa",
  "Suparnasa",
  "Swathantra Kapisa",
  "Tayal",
  "Tharakayanam",
  "Thingal",
  "Titwal",
  "Tushar",
  "Udbahu",
  "Udhalaka",
  "Uditha Gautham",
  "Udithya",
  "Upamanyu Vasishtasa",
  "Upamanyu",
  "Upathya",
  "Vadoola  / Vadulasa",
  "Vainya",
  "Vardheyasa",
  "Vashishtha",
  "Veethahavya",
  "Vishnordhageerasa",
  "Vishnu Vridhha",
  "Vishwamitra",
  "Yaska",
  "Others",
  "Don't know"]

  export default {
    familyValbro,familyValsis,
    profileoption,religionoption,
    chidoption,languageoption,
    statusoption,annualoption,gotram,
    familyVal,heightoption,countryoption,
    familyStatus,familyType,
    stateoption,cityoption,rassioption,castoption,degreeoption,employoption,employeeption,motherTongue
  }

//   export const hobbies=[
//     {title:"Acting",value:1},
//     {title:'Animal breeding',value:2},
//     {title:'Art / Handicraft',value:3},
//     {title:'Astrology / Palmistry / Numerology',value:},
//     {title:'Astronomy',value:},
//     {title:'Bird watching',value:},
//     {title:'Collectibles',value:},
//     {title:'Cooking',value:},
//     {title:'Dancing',value:},
//     {title:'DIY(do it yourself) projects',value:},
//     {title:'Film-making','Fishing',value:},
//     {title:'Gardening / Landscaping',value:},
//     {title:'Graphology',value:},
//     {title:'Ham radio',value:},
//     {title:'Home / Interior decoration',value:},
//     {title:'Hunting',  value:},
//     {title:'Model building',value:},
//     {title:'Painting / Drawing',value:},
//     {title:'Photography',value:},
//     {title:'Playing musical instruments',value:},
//     {title:'Singing',value:},
//     {title:'Solving Crosswords', value:},
//     {title:'Puzzles'value:},
//   // Will tell you later
// ]





   
