// import {Country,State,City}  from 'country-state-city';  



export const ageDiff = [
  { value: 18 },
  { value: 19 },
  { value: 20 },
  { value: 21 },
  { value: 22 },
  { value: 23 },
  { value: 24 },
  { value: 25 },
  { value: 0 },
  { value: 1 },
  { value: 2 },
  { value: 4 },
  { value: 0 },
  { value: 1 },
  { value: 2 },
  { value: 4 },
  { value: 0 },
  { value: 1 },
  { value: 2 },
  { value: 4 },
  { value: 0 },
  { value: 1 },
  { value: 2 },
  { value: 4 },
];



export const familyValbro = [
  { title: "0" },
  { title: "1" },
  { title: "2" },
  { title: "3" },
];



// no of sister
export const familyValsis = [
  { title: "0" },
  { title: "1" },
  { title: "2" },
  { title: "3" },
];

export const profileoption = [
    { title: "Self" },
    { title: "Son" },
    { title: "Daughter" },
    { title: "Brother" },
    { title: "Sister" },
    { title: "Other" },
  ];
  export const religionoption = [
    { title: "Hindu" },
    { title: "Muslim" },
    { title: "Christian" },
    { title: "Sikh" },
    { title: "Buddhist" },
    { title: "Jain" },
    { title: "Other Religions" },
    { title: "Any" },
  ];
  // chidoption
  export const chidoption = [
    { title: "0",key:0 },
    { title: "1" ,key:1},
    { title: "2" ,key:2},
    { title: "3" ,key:3},
    { title: "4" ,key:4},
  ];
  // languageoption
  export const languageoption = [
    { title: "Hindi" ,key:1},
    { title: "Gujarati" ,key:2},
    { title: "Marathi" ,key:3},
    { title: "Punjabi" ,key:4},
    { title: "Konkani" ,key:5},
    { title: "English" ,key:6},
    { title: "Halabi" ,key:7},
  ];
  export const statusoption = [
    { value: "SINGLE" ,title:"Single"},
    { value: "DIVORCED" ,title:"Divorce"},
    { value: "AWAITING_DIVORCE" ,title:"Awaiting Divorce"},
    { value: "WIDOW",title:"Widow" },
    { value: "ANY",title:"Any" },
    { value: "NOT_SPECIFIED" ,title:"Not Specified"},
  ];
  
  export const annualoption = [
    { title: "Not Working" ,value:0},
    { title: "Upto INR 1 Lakh" ,value:1},
    { title: "INR 1 Lakh to 2 Lakh" ,value:2},
    { title: "INR 2 Lakh to 4 Lakh" ,value:3},
    { title: "INR 4 Lakh to 7 Lakh" ,value:4},
    { title: "INR 7 Lakh to 10 Lakh",value:5 },
    { title: "INR 10 Lakh to 15 Lakh" ,value:6},
    { title: "INR 15 Lakh to 20 Lakh" ,value:7},
    { title: "INR 20 Lakh to 30 Lakh",value:8 },
    { title: "INR 30 Lakh to 50 Lakh" ,value:9},
    { title: "INR 50 Lakh to 90 Lakh" ,value:10},
    { title: "Above 90 Lakh" ,value:11},
    { title: "Not Specified" ,value:12}
  ];
  export const familyVal = [
    { value: "ORTHODOX" ,title:"Orthodox"},
    { value: "TRADITIONAL",title:"Traditional" },
    { value: "MODERATE" ,title:"Moderate"},
    { value: "LIBERAL" ,title:"Liberal"},
  ];
  export const heightoption = [
    { title: "4 ft 0 in" ,value:0},
    { title: "4 ft 1 in" ,value:1},
    { title: "4 ft 2 in" ,value:2},
    { title: "4 ft 3 in" ,value:3},
    { title: "4 ft 4 in" ,value:4},
    { title: "4 ft 5 in" ,value:5},
    { title: "4 ft 6 in" ,value:6},
    { title: "4 ft 7 in" ,value:7},
    { title: "4 ft 8 in" ,value:8},
    { title: "4 ft 9 in" ,value:9},
    { title: "4 ft 10 in" ,value:10},
    { title: "4 ft 11 in" ,value:11},
    { title: "5 ft 0 in	" ,value:12},
    { title: "5 ft 1 in" ,value:13},
    { title: "5 ft 2 in" ,value:14},
    { title: "5 ft 3 in" ,value:15},
    { title: "5 ft 4 in" ,value:16},
    { title: "5 ft 5 in" ,value:17},
    { title: "5 ft 6 in" ,value:18},
    { title: "5 ft 7 in" ,value:19},
    { title: "5 ft 8 in" ,value:20},
    { title: "5 ft 9 in" ,value:21},
    { title: "5 ft 10 in" ,value:22},
    { title: "5 ft 11 in" ,value:23},
    { title: "Not Specified" ,value:24},
    
  ];
  // Loction
  export const countryoption = 
 [
   {"code": "af", "dial_code": "+93", "name": "Afghanistan"},
  {"code": "al", "dial_code": "+355", "name": "Albania"}, 
  {"code": "dz", "dial_code": "+213", "name": "Algeria"}, 
  {"code": "ad", "dial_code": "+376", "name": "Andorra"}, 
  {"code": "ao", "dial_code": "+244", "name": "Angola"},
{"code": "ai", "dial_code": "+1264", "name": "Anguilla"},
{"code": "ag", "dial_code": "+1268", "name": "Antigua and Barbuda"},
{"code": "ar", "dial_code": "+54", "name": "Argentina"},
{"code": "am", "dial_code": "+374", "name": "Armenia"},
{"code": "aw", "dial_code": "+297", "name": "Aruba"},
{"code": "au", "dial_code": "+61", "name": "Australia"},
{"code": "at", "dial_code": "+43", "name": "Austria"},
{"code": "az", "dial_code": "+994", "name": "Azerbaijan"},
{"code": "bs", "dial_code": "+1242", "name": "Bahamas"},
{"code": "bh", "dial_code": "+973", "name": "Bahrain"},
{"code": "bd", "dial_code": "+880", "name": "Bangladesh"},
{"code": "bb", "dial_code": "+1246", "name": "Barbados"},
{"code": "by", "dial_code": "+375", "name": "Belarus"},
{"code": "be", "dial_code": "+32", "name": "Belgium"},
{"code": "bz", "dial_code": "+501", "name": "Belize"},
{"code": "bj", "dial_code": "+229", "name": "Benin"},
{"code": "bm", "dial_code": "+1441", "name": "Bermuda"},
{"code": "bt", "dial_code": "+975", "name": "Bhutan"},
{"code": "bo", "dial_code": "+591", "name": "Bolivia"},
{"code": "ba", "dial_code": "+387", "name": "Bosnia and Herzegovina"},
{"code": "bw", "dial_code": "+267", "name": "Botswana"},
{"code": "br", "dial_code": "+55", "name": "Brazil"},
{"code": "bn", "dial_code": "+673", "name": "Brunei Darussalam"},
{"code": "bg", "dial_code": "+359", "name": "Bulgaria"},
{"code": "bf", "dial_code": "+226", "name": "Burkina Faso"},
{"code": "bi", "dial_code": "+257", "name": "Burundi"},
{"code": "kh", "dial_code": "+855", "name": "Cambodia"},
{"code": "cm", "dial_code": "+237", "name": "Cameroon"},
{"code": "ca", "dial_code": "+1", "name": "Canada"},
{"code": "cv", "dial_code": "+238", "name": "Cape Verde"},
{"code": "ky", "dial_code": "+ 345", "name": "Cayman Islands"},
{"code": "cf", "dial_code": "+236", "name": "Central African Republic"},
{"code": "td", "dial_code": "+235", "name": "Chad"},
{"code": "cl", "dial_code": "+56", "name": "Chile"},
{"code": "cn", "dial_code": "+86", "name": "China"},
{"code": "cx", "dial_code": "+61", "name": "Christmas Island"},
{"code": "cc", "dial_code": "+61", "name": "Cocos (Keeling) Islands"},
{"code": "co", "dial_code": "+57", "name": "Colombia"},
{"code": "km", "dial_code": "+269", "name": "Comoros"},
{"code": "cg", "dial_code": "+242", "name": "Congo"},
{"code": "ck", "dial_code": "+682", "name": "Cook Islands"},
{"code": "cr", "dial_code": "+506", "name": "Costa Rica"},
{"code": "ci", "dial_code": "+225", "name": "Cote D'Ivoire"},
{"code": "hr", "dial_code": "+385", "name": "Croatia"},
{"code": "cu", "dial_code": "+53", "name": "Cuba"},
{"code": "cy", "dial_code": "+537", "name": "Cyprus"},
{"code": "cz", "dial_code": "+420", "name": "Czech Republic"},
{"code": "cd", "dial_code": "+243", "name": "Democratic Republic of the Congo"},
{"code": "dk", "dial_code": "+45", "name": "Denmark"},
{"code": "dj", "dial_code": "+253", "name": "Djibouti"},
{"code": "dm", "dial_code": "+1767", "name": "Dominica"},
{"code": "do", "dial_code": "+1849", "name": "Dominican Republic"},
{"code": "ec", "dial_code": "+593", "name": "Ecuador"},
{"code": "eg", "dial_code": "+20", "name": "Egypt"},
{"code": "sv", "dial_code": "+503", "name": "El Salvador"},
{"code": "gq", "dial_code": "+240", "name": "Equatorial Guinea"},
{"code": "er", "dial_code": "+291", "name": "Eritrea"},
{"code": "ee", "dial_code": "+372", "name": "Estonia"},
{"code": "et", "dial_code": "+251", "name": "Ethiopia"},
{"code": "fk", "dial_code": "+500", "name": "Falkland Islands"},
{"code": "fo", "dial_code": "+298", "name": "Faroe Islands"},
{"code": "fm", "dial_code": "+691", "name": "Federated States of Micronesia"},
{"code": "fj", "dial_code": "+679", "name": "Fiji"},
{"code": "fi", "dial_code": "+358", "name": "Finland"},
{"code": "fr", "dial_code": "+33", "name": "France"},
{"code": "gf", "dial_code": "+594", "name": "French Guiana"},
{"code": "pf", "dial_code": "+689", "name": "French Polynesia"},
{"code": "tf", "dial_code": "+262", "name": "French Southern Territories"},
{"code": "ga", "dial_code": "+241", "name": "Gabon"},
{"code": "gm", "dial_code": "+220", "name": "Gambia"},
{"code": "ge", "dial_code": "+995", "name": "Georgia"},
{"code": "de", "dial_code": "+49", "name": "Germany"},
{"code": "gh", "dial_code": "+233", "name": "Ghana"},
{"code": "gi", "dial_code": "+350", "name": "Gibraltar"},
{"code": "gb", "dial_code": "+44", "name": "Great Britain (UK)"},
{"code": "gr", "dial_code": "+30", "name": "Greece"},
{"code": "gl", "dial_code": "+299", "name": "Greenland"},
{"code": "gd", "dial_code": "+1473", "name": "Grenada"},
{"code": "gp", "dial_code": "+590", "name": "Guadeloupe"},
{"code": "gt", "dial_code": "+502", "name": "Guatemala"},
{"code": "gn", "dial_code": "+224", "name": "Guinea"},
{"code": "gw", "dial_code": "+245", "name": "Guinea-Bissau"},
{"code": "gy", "dial_code": "+595", "name": "Guyana"},
{"code": "ht", "dial_code": "+509", "name": "Haiti"},
{"code": "hn", "dial_code": "+504", "name": "Honduras"},
{"code": "hk", "dial_code": "+852", "name": "Hong Kong"},
{"code": "hu", "dial_code": "+36", "name": "Hungary"},
{"code": "is", "dial_code": "+354", "name": "Iceland"},
{"code": "in", "dial_code": "+91", "name": "India"},
{"code": "id", "dial_code": "+62", "name": "Indonesia"},
{"code": "ir", "dial_code": "+98", "name": "Iran"},
{"code": "iq", "dial_code": "+964", "name": "Iraq"},
{"code": "ie", "dial_code": "+353", "name": "Ireland"},
{"code": "il", "dial_code": "+972", "name": "Israel"},
{"code": "it", "dial_code": "+39", "name": "Italy"},
{"code": "jm", "dial_code": "+1876", "name": "Jamaica"},
{"code": "jp", "dial_code": "+81", "name": "Japan"},
{"code": "jo", "dial_code": "+962", "name": "Jordan"},
{"code": "kz", "dial_code": "+7 7", "name": "Kazakhstan"},
{"code": "ke", "dial_code": "+254", "name": "Kenya"},
{"code": "ki", "dial_code": "+686", "name": "Kiribati"},
{"code": "kp", "dial_code": "+850", "name": "North Korea"},
{"code": "kr", "dial_code": "+82", "name": "South Korea"},
{"code": "kw", "dial_code": "+965", "name": "Kuwait"},
{"code": "kg", "dial_code": "+996", "name": "Kyrgyzstan"},
{"code": "la", "dial_code": "+856", "name": "Laos"},
{"code": "lv", "dial_code": "+371", "name": "Latvia"},
{"code": "lb", "dial_code": "+961", "name": "Lebanon"},
{"code": "ls", "dial_code": "+266", "name": "Lesotho"},
{"code": "lr", "dial_code": "+231", "name": "Liberia"},
{"code": "ly", "dial_code": "+218", "name": "Libya"},
{"code": "li", "dial_code": "+423", "name": "Liechtenstein"},
{"code": "lt", "dial_code": "+370", "name": "Lithuania"},
{"code": "lu", "dial_code": "+352", "name": "Luxembourg"},
{"code": "mo", "dial_code": "+853", "name": "Macao"},
{"code": "mk", "dial_code": "+389", "name": "Macedonia"},
{"code": "mg", "dial_code": "+261", "name": "Madagascar"},
{"code": "mw", "dial_code": "+265", "name": "Malawi"},
{"code": "my", "dial_code": "+60", "name": "Malaysia"},
{"code": "mv", "dial_code": "+960", "name": "Maldives"},
{"code": "ml", "dial_code": "+223", "name": "Mali"},
{"code": "mt", "dial_code": "+356", "name": "Malta"},
{"code": "mh", "dial_code": "+692", "name": "Marshall Islands"},
{"code": "mq", "dial_code": "+596", "name": "Martinique"},
{"code": "mr", "dial_code": "+222", "name": "Mauritania"},
{"code": "mu", "dial_code": "+230", "name": "Mauritius"},
{"code": "yt", "dial_code": "+262", "name": "Mayotte"},
{"code": "mx", "dial_code": "+52", "name": "Mexico"},
{"code": "md", "dial_code": "+373", "name": "Moldova"},
{"code": "mc", "dial_code": "+377", "name": "Monaco"},
{"code": "mn", "dial_code": "+976", "name": "Mongolia"},
{"code": "ms", "dial_code": "+1664", "name": "Montserrat"},
{"code": "ma", "dial_code": "+212", "name": "Morocco"},
{"code": "mz", "dial_code": "+258", "name": "Mozambique"},
{"code": "mm", "dial_code": "+95", "name": "Myanmar"},
{"code": "na", "dial_code": "+264", "name": "Namibia"},
{"code": "nr", "dial_code": "+674", "name": "Nauru"},
{"code": "np", "dial_code": "+977", "name": "Nepal"},
{"code": "nl", "dial_code": "+31", "name": "Netherlands"},
{"code": "an", "dial_code": "+599", "name": "Netherlands Antilles"},
{"code": "nc", "dial_code": "+687", "name": "New Caledonia"},
{"code": "nz", "dial_code": "+64", "name": "New Zealand"},
{"code": "ni", "dial_code": "+505", "name": "Nicaragua"},
{"code": "ne", "dial_code": "+227", "name": "Niger"},
{"code": "ng", "dial_code": "+234", "name": "Nigeria"},
{"code": "nu", "dial_code": "+683", "name": "Niue"},
{"code": "nf", "dial_code": "+672", "name": "Norfolk Island"},
{"code": "mp", "dial_code": "+1670", "name": "Northern Mariana Islands"},
{"code": "no", "dial_code": "+47", "name": "Norway"},
{"code": "gg", "dial_code": "+44", "name": "NULL"},
{"code": "om", "dial_code": "+968", "name": "Oman"},
{"code": "pk", "dial_code": "+92", "name": "Pakistan"},
{"code": "pw", "dial_code": "+680", "name": "Palau"},
{"code": "ps", "dial_code": "+970", "name": "Palestinian Territory"},
{"code": "pa", "dial_code": "+507", "name": "Panama"},
{"code": "pg", "dial_code": "+675", "name": "Papua New Guinea"},
{"code": "py", "dial_code": "+595", "name": "Paraguay"},
{"code": "pe", "dial_code": "+51", "name": "Peru"},
{"code": "ph", "dial_code": "+63", "name": "Philippines"},
{"code": "pn", "dial_code": "+872", "name": "Pitcairn"},
{"code": "pl", "dial_code": "+48", "name": "Poland"},
{"code": "pt", "dial_code": "+351", "name": "Portugal"},
{"code": "qa", "dial_code": "+974", "name": "Qatar"},
{"code": "re", "dial_code": "+262", "name": "Reunion"},
{"code": "ro", "dial_code": "+40", "name": "Romania"},
{"code": "ru", "dial_code": "+7", "name": "Russian Federation"},
{"code": "rw", "dial_code": "+250", "name": "Rwanda"},
{"code": "gs", "dial_code": "+500", "name": "S. Georgia and S. Sandwich Islands"},
{"code": "sh", "dial_code": "+290", "name": "Saint Helena"},
{"code": "kn", "dial_code": "+1869", "name": "Saint Kitts and Nevis"},
{"code": "lc", "dial_code": "+1758", "name": "Saint Lucia"},
{"code": "pm", "dial_code": "+508", "name": "Saint Pierre and Miquelon"},
{"code": "vc", "dial_code": "+1784", "name": "Saint Vincent and the Grenadines"},
{"code": "ws", "dial_code": "+685", "name": "Samoa"},
{"code": "sm", "dial_code": "+378", "name": "San Marino"},
{"code": "st", "dial_code": "+239", "name": "Sao Tome and Principe"},
{"code": "sa", "dial_code": "+966", "name": "Saudi Arabia"},
{"code": "sn", "dial_code": "+221", "name": "Senegal"},
{"code": "sc", "dial_code": "+248", "name": "Seychelles"},
{"code": "sl", "dial_code": "+232", "name": "Sierra Leone"},
{"code": "sg", "dial_code": "+65", "name": "Singapore"},
{"code": "sk", "dial_code": "+421", "name": "Slovakia"},
{"code": "si", "dial_code": "+386", "name": "Slovenia"},
{"code": "sb", "dial_code": "+677", "name": "Solomon Islands"},
{"code": "so", "dial_code": "+252", "name": "Somalia"},
{"code": "za", "dial_code": "+27", "name": "South Africa"},
{"code": "es", "dial_code": "+34", "name": "Spain"},
{"code": "lk", "dial_code": "+94", "name": "Sri Lanka"},
{"code": "sd", "dial_code": "+249", "name": "Sudan"},
{"code": "sr", "dial_code": "+597", "name": "Suriname"},
{"code": "sj", "dial_code": "+47", "name": "Svalbard and Jan Mayen"},
{"code": "sz", "dial_code": "+268", "name": "Swaziland"},
{"code": "se", "dial_code": "+46", "name": "Sweden"},
{"code": "ch", "dial_code": "+41", "name": "Switzerland"},
{"code": "sy", "dial_code": "+963", "name": "Syria"},
{"code": "tw", "dial_code": "+886", "name": "Taiwan"},
{"code": "tj", "dial_code": "+992", "name": "Tajikistan"},
{"code": "tz", "dial_code": "+255", "name": "Tanzania"},
{"code": "th", "dial_code": "+66", "name": "Thailand"},
{"code": "tg", "dial_code": "+228", "name": "Togo"},
{"code": "tk", "dial_code": "+690", "name": "Tokelau"},
{"code": "to", "dial_code": "+676", "name": "Tonga"},
{"code": "tt", "dial_code": "+1868", "name": "Trinidad and Tobago"},
{"code": "tn", "dial_code": "+216", "name": "Tunisia"},
{"code": "tr", "dial_code": "+90", "name": "Turkey"},
{"code": "tm", "dial_code": "+993", "name": "Turkmenistan"},
{"code": "tc", "dial_code": "+1649", "name": "Turks and Caicos Islands"},
{"code": "tv", "dial_code": "+688", "name": "Tuvalu"},
{"code": "ug", "dial_code": "+256", "name": "Uganda"},
{"code": "ua", "dial_code": "+380", "name": "Ukraine"},
{"code": "ae", "dial_code": "+971", "name": "United Arab Emirates"},
{"code": "us", "dial_code": "+1", "name": "United States of America"},
{"code": "uy", "dial_code": "+598", "name": "Uruguay"},
{"code": "uz", "dial_code": "+998", "name": "Uzbekistan"},
{"code": "vu", "dial_code": "+678", "name": "Vanuatu"},
{"code": "ve", "dial_code": "+58", "name": "Venezuela"},
{"code": "vn", "dial_code": "+84", "name": "Vietnam"},
{"code": "vg", "dial_code": "+1284", "name": "Virgin Islands (British)"},
{"code": "vi", "dial_code": "+1340", "name": "Virgin Islands (U.S.)"},
{"code": "wf", "dial_code": "+681", "name": "Wallis and Futuna"},
{"code": "eh", "dial_code": "+212", "name": "Western Sahara"},
{"code": "ye", "dial_code": "+967", "name": "Yemen"},
{"code": "zm", "dial_code": "+260", "name": "Zambia"},
{"code": "zw", "dial_code": "+263", "name": "Zimbabwe"}
  ];

  export const citizenshipoption = [
    { title: "India" },
    { title: "China" },
    { title: "Germany" },
    { title: "Italy" },
  
    { title: "America" },
  ];

  export const raashi =[
    'Aries',
    'Taurus',
    'Gemini',
    'Cancer',
    'Leo',
    'Virgo',
    'Libra',
    'Scorpio',
    'Sagittarius',
    'Capricorn',
    'Aquarius',
    'Pisces',

  ]
  export const stateoption = [
    { title: "Bihar" },
    { title: "Gujarat" },
    { title: "Karnataka" },
    { title: "Maharashtra" },
    { title: "Orissa" },
    { title: "Rajasthan" },
    { title: "Punjab" },
  ];
  export const cityoption = [
    { title: "Mumbai" },
    { title: "Pune" },
    { title: "Hydrabad" },
    { title: "Nagpur" },
  ];
  export const motherTongue=[{ title: "Aka" },
  { title: "Arabic" },
  { title: "Arunachali" },
  { title: "Assamese" },
  { title: "Awadhi" },
  { title: "Baluchi" },
  { title: "Bengali" },
  { title: "Bhojpuri" },
  { title: "Bhutia" },
  { title: "Brahui" },
  { title: "Brij" },
  { title: "Burmese" },
  { title: "Chattisgarhi" },
  { title: "Chinese" },
  { title: "Coorgi" },
  { title: "Dogri" },
  { title: "English" },
  { title: "French" },
  { title: "Garhwali" },
  { title: "Garo" },
  { title: "Gujarati" },
  { title: "Haryanavi" },
  { title: "Himachali/Pahari" },
  { title: "Hindi" },
  { title: "Hindko" },
  { title: "Kakbarak" },
  { title: "Kanauji" },
  { title: "Kannada" },
  { title: "Kashmiri" },
  { title: "Khandesi" },
  { title: "Khasi" },
  { title: "Konkani" },
  { title: "Koshali" },
  { title: "Kumaoni" },
  { title: "Kutchi" },
  { title: "Ladakhi" },
  { title: "Lepcha" },
  { title: "Magahi" },
  { title: "Maithili" },
  { title: "Malay" },
  { title: "Malayalam" },
  { title: "Manipuri" },
  { title: "Marathi" },
  { title: "Marwari" },
  { title: "Miji" },
  { title: "Mizo" },
  { title: "Monpa" },
  { title: "Nepali" },
  { title: "Odia" },
  { title: "Pashto" },
  { title: "Persian" },
  { title: "Punjabi" },
  { title: "Rajasthani" },
  { title: "Russian" },
  { title: "Sanskrit" },
  { title: "Santhali" },
  { title: "Seraiki" },
  { title: "Sindhi" },
  { title: "Sinhala" },
  { title: "Sourashtra" },
  { title: "Spanish" },
  { title: "Swedish" },
  { title: "Tagalog" },
  { title: "Tamil" },
  { title: "Telugu" },
  { title: "Tulu" },
  { title: "Urdu" },
  { title: "Other" },
]
  export const rassioption = [
        { title: "Aries" },
        { title: "Gemini" },
        { title: "Cancer" },
        { title: "Leo" },
        { title: "Virgo" },
        { title: "Taurus" },
        { title: "Libra" },
        { title: "Scorpio" },
        { title: "Sagittarius" },
        { title: "Capricorn" },
        { title: "Aquarius" },
        { title: "Pisces" },
    
  ];
  export const castoption = [
    { title: "24 Manai Telugu Chettiar" },
    { title: "96 Kuli Maratha" },
    { title: "96K Kokanastha" },
    { title: "Adi Andhra" },
    { title: "Adi Dharmi" },
    { title: "Adi Dravida" },
    { title: "Adi Karnataka" },
    { title: "Agamudayar" },
    { title: "Agarwal" },
    { title: "Agnikula Kshatriya" },
    { title: "Agri" },
    { title: "Ahir" },
    { title: "Ahom" },
    { title: "Ambalavasi" },
    { title: "Arcot" },
    { title: "Arekatica" },
    { title: "Arora" },
    { title: "Arunthathiyar" },
    { title: "Arya Vysya" },
    { title: "Aryasamaj" },
    { title: "Ayyaraka" },
    { title: "Badaga" },
    { title: "Baghel/Pal/Gaderiya" },
    { title: "Bahi" },
    { title: "Baidya" },
    { title: "Baishnab" },
    { title: "Baishya" },
    { title: "Bajantri" },
    { title: "Balija" },
    { title: "Balija - Naidu" },
    { title: "Banayat Oriya" },
    { title: "Banik" },
    { title: "Baniya" },
    { title: "Barai" },
    { title: "Bari" },
    { title: "Barnwal" },
    { title: "Barujibi" },
    { title: "Bengali" },
    { title: "Besta" },
    { title: "Bhandari" },
    { title: "Bhatia" },
    { title: "Bhatraju" },
    { title: "Bhavsar" },
    { title: "Bhovi" },
    { title: "Billava" },
    { title: "Boya/Nayak/Naik" },
    { title: "Boyer" },
    { title: "Brahmbatt" },
    { title: "Brahmin" },
    { title: "Brahmin - Anavil" },
    { title: "Brahmin - Audichya" },
    { title: "Brahmin - Barendra" },
    { title: "Brahmin - Bengali" },
    { title: "Brahmin - Bhatt" },
    { title: "Brahmin - Bhumihar" },
    { title: "Brahmin - Brahmbhatt" },
    { title: "Brahmin - Dadhich/Dadheech" },
    { title: "Brahmin - Daivadnya" },
    { title: "Brahmin - Danua" },
    { title: "Brahmin - Deshastha" },
    { title: "Brahmin - Dhiman" },
    { title: "Brahmin - Dravida" },
    { title: "Brahmin - Embrandiri" },
    { title: "Brahmin - Garhwali" },
    { title: "Brahmin - Goswami" },
    { title: "Brahmin - Gour" },
    { title: "Brahmin - Gowd Saraswat" },
    { title: "Brahmin - Gujar Gour" },
    { title: "Brahmin - Gurukkal" },
    { title: "Brahmin - Halua" },
    { title: "Brahmin - Havyaka" },
    { title: "Brahmin - Himachali" },
    { title: "Brahmin - Hoysala" },
    { title: "Brahmin - Iyengar" },
    { title: "Brahmin - Iyer" },
    { title: "Brahmin - Jangid" },
    { title: "Brahmin - Jhadua" },
    { title: "Brahmin - Jhijhotiya" },
    { title: "Brahmin - Kannada Madhva" },
    { title: "Brahmin - Kanyakubja" },
    { title: "Brahmin - Karhade" },
    { title: "Brahmin - Kashmiri Pandit" },
    { title: "Brahmin - Kokanastha" },
    { title: "Brahmin - Kota" },
    { title: "Brahmin - Kulin" },
    { title: "Brahmin - Kumaoni" },
    { title: "Brahmin - Madhwa" },
    { title: "Brahmin - Maharashtrian" },
    { title: "Brahmin - Maithili" },
    { title: "Brahmin - Modh" },
    { title: "Brahmin - Mohyal" },
    { title: "Brahmin - Nagar" },
    { title: "Brahmin - Namboodiri" },
    { title: "Brahmin - Niyogi" },
    { title: "Brahmin - Niyogi Nandavariki" },
    { title: "Brahmin - Other" },
    { title: "Brahmin - Paliwal" },
    { title: "Brahmin - Panda" },
    { title: "Brahmin - Pareek" },
    { title: "Brahmin - Punjabi" },
    { title: "Brahmin - Pushkarna" },
    { title: "Brahmin - Rarhi" },
    { title: "Brahmin - Rudraj" },
    { title: "Brahmin - Sakaldwipi" },
    { title: "Brahmin - Sanadya" },
    { title: "Brahmin - Sanketi" },
    { title: "Brahmin - Saraswat" },
    { title: "Brahmin - Sarua" },
    { title: "Brahmin - Saryuparin" },
    { title: "Brahmin - Shivhalli" },
    { title: "Brahmin - Shrimali" },
    { title: "Brahmin - Smartha" },
    { title: "Brahmin - Sri Vaishnava" },
    { title: "Brahmin - Stanika" },
    { title: "Brahmin - Tyagi" },
    { title: "Brahmin - Vaidiki" },
    { title: "Brahmin - Vaikhanasa" },
    { title: "Brahmin - Velanadu" },
    { title: "Brahmin - Viswabrahmin" },
    { title: "Brahmin - Vyas" },
    { title: "Brahmo" },
    { title: "Buddar" },
    { title: "Bunt (Shetty)" },
    { title: "CKP" },
    { title: "Chalawadi Holeya" },
    { title: "Chambhar" },
    { title: "Chandravanshi Kahar" },
    { title: "Chasa" },
    { title: "Chattada Sri Vaishnava" },
    { title: "Chaudary" },
    { title: "Chaurasia" },
    { title: "Chekkala - Nair" },
    { title: "Chennadasar" },
    { title: "Cheramar" },
    { title: "Chettiar" },
    { title: "Chhetri" },
    { title: "Chippolu/Mera" },
    { title: "Coorgi" },
    { title: "Devadiga" },
    { title: "Devanga" },
    { title: "Devar/Thevar/Mukkulathor" },
    { title: "Devendra Kula Vellalar" },
    { title: "Dhangar" },
    { title: "Dheevara" },
    { title: "Dhiman" },
    { title: "Dhoba" },
    { title: "Dhobi" },
    { title: "Digambar" },
    { title: "Dommala" },
    { title: "Dusadh" },
    { title: "Ediga" },
    { title: "Ezhava" },
    { title: "Ezhuthachan" },
    { title: "Gabit" },
    { title: "Ganakar" },
    { title: "Gandla" },
    { title: "Ganiga" },
    { title: "Garhwali" },
    { title: "Gatti" },
    { title: "Gavali" },
    { title: "Gavara" },
    { title: "Ghumar" },
    { title: "Goala" },
    { title: "Goan" },
    { title: "Goswami" },
    { title: "Goud" },
    { title: "Gounder" },
    { title: "Gowda" },
    { title: "Gramani" },
    { title: "Gudia" },
    { title: "Gujarati" },
    { title: "Gujjar" },
    { title: "Gupta" },
    { title: "Guptan" },
    { title: "Gurjar" },
    { title: "Halwai" },
    { title: "Hegde" },
    { title: "Helava" },
    { title: "Hugar (Jeer)" },
    { title: "Intercaste" },
    { title: "Jaalari" },
    { title: "Jaiswal" },
    { title: "Jandra" },
    { title: "Jangam" },
    { title: "Jat" },
    { title: "Jatav" },
    { title: "Jetty Malla" },
    { title: "Kachara" },
    { title: "Kaibarta" },
    { title: "Kakkalan" },
    { title: "Kalar" },
    { title: "Kalinga" },
    { title: "Kalinga Vysya" },
    { title: "Kalita" },
    { title: "Kalwar" },
    { title: "Kamboj" },
    { title: "Kamma" },
    { title: "Kamma Naidu" },
    { title: "Kammala" },
    { title: "Kaniyan" },
    { title: "Kannada Mogaveera" },
    { title: "Kansari" },
    { title: "Kanu" },
    { title: "Kapu" },
    { title: "Kapu Naidu" },
    { title: "Karana" },
    { title: "Karmakar" },
    { title: "Kartha" },
    { title: "Karuneegar" },
    { title: "Kasar" },
    { title: "Kashyap" },
    { title: "Kavuthiyya/Ezhavathy" },
    { title: "Kayastha" },
    { title: "Khandayat" },
    { title: "Khandelwal" },
    { title: "Kharwar" },
    { title: "Khatik" },
    { title: "Khatri" },
    { title: "Kirar" },
    { title: "Koli" },
    { title: "Koli Patel" },
    { title: "Kongu Vellala Gounder" },
    { title: "Konkani" },
    { title: "Korama" },
    { title: "Kori" },
    { title: "Koshti" },
    { title: "Krishnavaka" },
    { title: "Kshatriya" },
    { title: "Kshatriya - Bhavasar" },
    { title: "Kshatriya/Raju/Varma" },
    { title: "Kudumbi" },
    { title: "Kulal" },
    { title: "Kulalar" },
    { title: "Kulita" },
    { title: "Kumawat" },
    { title: "Kumbara" },
    { title: "Kumbhakar/Kumbhar" },
    { title: "Kumhar" },
    { title: "Kummari" },
    { title: "Kunbi" },
    { title: "Kurava" },
    { title: "Kuravan" },
    { title: "Kurmi" },
    { title: "Kurmi Kshatriya" },
    { title: "Kuruba" },
    { title: "Kuruhina Shetty" },
    { title: "Kurumbar" },
    { title: "Kurup" },
    { title: "Kushwaha" },
    { title: "Kutchi" },
    { title: "Lambadi/Banjara" },
    { title: "Lambani" },
    { title: "Leva Patil" },
    { title: "Lingayath" },
    { title: "Lohana" },
    { title: "Lohar" },
    { title: "Loniya/Lonia/Lunia" },
    { title: "Lubana" },
    { title: "Madhesiya" },
    { title: "Madiga" },
    { title: "Mahajan" },
    { title: "Mahar" },
    { title: "Maharashtrian" },
    { title: "Mahendra" },
    { title: "Maheshwari" },
    { title: "Mahindra" },
    { title: "Mahishya" },
    { title: "Majabi" },
    { title: "Mala" },
    { title: "Malayalee Variar" },
    { title: "Mali" },
    { title: "Mallah" },
    { title: "Mangalorean" },
    { title: "Maniyani" },
    { title: "Mannadiar" },
    { title: "Mannan" },
    { title: "Mapila" },
    { title: "Marar" },
    { title: "Maratha" },
    { title: "Maratha - Gomantak" },
    { title: "Maruthuvar" },
    { title: "Marvar" },
    { title: "Marwari" },
    { title: "Matang" },
    { title: "Maurya" },
    { title: "Meda" },
    { title: "Medara" },
    { title: "Meena" },
    { title: "Meenavar" },
    { title: "Meghwal" },
    { title: "Mehra" },
    { title: "Menon" },
    { title: "Meru Darji" },
    { title: "Modak" },
    { title: "Mogaveera" },
    { title: "Monchi" },
    { title: "Mudaliar" },
    { title: "Mudaliar - Arcot" },
    { title: "Mudaliar - Saiva" },
    { title: "Mudaliar - Senguntha" },
    { title: "Mudiraj" },
    { title: "Munnuru Kapu" },
    { title: "Muthuraja" },
    { title: "Naagavamsam" },
    { title: "Nadar" },
    { title: "Nagaralu" },
    { title: "Nai" },
    { title: "Naicken" },
    { title: "Naicker" },
    { title: "Naidu" },
    { title: "Naik" },
    { title: "Nair" },
    { title: "Nair - Vaniya" },
    { title: "Nair - Velethadathu" },
    { title: "Nair - Vilakkithala" },
    { title: "Namasudra" },
    { title: "Nambiar" },
    { title: "Nambisan" },
    { title: "Namdev" },
    { title: "Namosudra" },
    { title: "Napit" },
    { title: "Nayak" },
    { title: "Nayaka" },
    { title: "Neeli" },
    { title: "Nepali" },
    { title: "Nhavi" },
    { title: "OBC - Barber/Naayee" },
    { title: "Oswal" },
    { title: "Otari" },
    { title: "Padmasali" },
    { title: "Panchal" },
    { title: "Pandaram" },
    { title: "Panicker" },
    { title: "Paravan" },
    { title: "Parit" },
    { title: "Parkava Kulam" },
    { title: "Partraj" },
    { title: "Pasi" },
    { title: "Paswan" },
    { title: "Patel" },
    { title: "Patel - Desai" },
    { title: "Patel - Dodia" },
    { title: "Patel - Kadva" },
    { title: "Patel - Leva" },
    { title: "Patnaick" },
    { title: "Patra" },
    { title: "Patwa" },
    { title: "Perika" },
    { title: "Pillai" },
    { title: "Pisharody" },
    { title: "Poduval" },
    { title: "Poosala" },
    { title: "Porwal" },
    { title: "Prajapati" },
    { title: "Pulaya" },
    { title: "Punjabi" },
    { title: "Raigar" },
    { title: "Rajaka" },
    { title: "Rajaka/Chakali/Dhobi" },
    { title: "Rajbhar" },
    { title: "Rajput" },
    { title: "Rajput - Garhwali" },
    { title: "Rajput - Kumaoni" },
    { title: "Rajput - Lodhi" },
    { title: "Ramdasia" },
    { title: "Ramgharia" },
    { title: "Rauniyar" },
    { title: "Ravidasia" },
    { title: "Rawat" },
    { title: "Reddiar" },
    { title: "Reddy" },
    { title: "Relli" },
    { title: "SSK" },
    { title: "Sadgop" },
    { title: "Sagara - Uppara" },
    { title: "Saha" },
    { title: "Sahu" },
    { title: "Saini" },
    { title: "Saiva Vellala" },
    { title: "Saliya" },
    { title: "Sambava" },
    { title: "Satnami" },
    { title: "Savji" },
    { title: "Scheduled Caste (SC)" },
    { title: "Scheduled Tribe (ST)" },
    { title: "Senai Thalaivar" },
    { title: "Sepahia" },
    { title: "Setti Balija" },
    { title: "Shah" },
    { title: "Shilpkar" },
    { title: "Shimpi" },
    { title: "Sindhi" },
    { title: "Sindhi - Bhanusali" },
    { title: "Sindhi - Bhatia" },
    { title: "Sindhi - Chhapru" },
    { title: "Sindhi - Dadu" },
    { title: "Sindhi - Hyderabadi" },
    { title: "Sindhi - Larai" },
    { title: "Sindhi - Lohana" },
    { title: "Sindhi - Rohiri" },
    { title: "Sindhi - Sehwani" },
    { title: "Sindhi - Thatai" },
    { title: "Sindhi-Amil" },
    { title: "Sindhi-Baibhand" },
    { title: "Sindhi-Larkana" },
    { title: "Sindhi-Sahiti" },
    { title: "Sindhi-Sakkhar" },
    { title: "Sindhi-Shikarpuri" },
    { title: "Somvanshi" },
    { title: "Sonar" },
    { title: "Soni" },
    { title: "Sourashtra" },
    { title: "Sowrashtra" },
    { title: "Sozhiya Vellalar" },
    { title: "Sri Vaishnava" },
    { title: "Srisayana" },
    { title: "Subarna Banik" },
    { title: "Sugali (Naika)" },
    { title: "Sundhi" },
    { title: "Surya Balija" },
    { title: "Sutar" },
    { title: "Suthar" },
    { title: "Swakula Sali" },
    { title: "Swarnakar" },
    { title: "Tamboli" },
    { title: "Tamil Yadava" },
    { title: "Tanti" },
    { title: "Tantuway" },
    { title: "Telaga" },
    { title: "Teli" },
    { title: "Telugu" },
    { title: "Thachar" },
    { title: "Thakkar" },
    { title: "Thakur" },
    { title: "Thandan" },
    { title: "Thigala" },
    { title: "Thiyya" },
    { title: "Thuluva Vellala" },
    { title: "Tili" },
    { title: "Togata" },
    { title: "Turupu Kapu" },
    { title: "Udayar" },
    { title: "Urali Gounder" },
    { title: "Urs" },
    { title: "Vada Balija" },
    { title: "Vadagalai" },
    { title: "Vaddera" },
    { title: "Vaduka" },
    { title: "Vaish" },
    { title: "Vaish - Dhaneshawat" },
    { title: "Vaishnav" },
    { title: "Vaishnav - Bhatia" },
    { title: "Vaishnav - Vania" },
    { title: "Vaishya" },
    { title: "Vallala" },
    { title: "Valluvan" },
    { title: "Valmiki" },
    { title: "Vanika Vyshya" },
    { title: "Vaniya Chettiar" },
    { title: "Vanjara" },
    { title: "Vankar" },
    { title: "Vannan" },
    { title: "Vannar" },
    { title: "Vanniyakullak Kshatriya" },
    { title: "Vanniyar" },
    { title: "Variar" },
    { title: "Varshney" },
    { title: "Veera Saivam" },
    { title: "Veerashaiva" },
    { title: "Velaan" },
    { title: "Velama" },
    { title: "Velar" },
    { title: "Vellalar" },
    { title: "Veluthedathu - Nair" },
    { title: "Vettuva Gounder" },
    { title: "Vishwakarma" },
    { title: "Viswabrahmin" },
    { title: "Vokaliga" },
    { title: "Vokkaliga" },
    { title: "Vysya" },
    { title: "Waada Balija" },
    { title: "Yadav" },
    { title: "Yellapu" },
    { title: "Other" },
  ];
  export const degreeoption = [
    { title: "BE" },
    { title: "MCA" },
    { title: "MSC" },
    { title: "BSC" },
  ];
  export const employoption = [
    { title: "Self Employed" ,value:"SELFEMPLOYED"},
    { title: "Government" ,value:"GOVERNMENT"},
    { title: "Private" ,value:"PRIVATE"},
    { title: "Bussiness" ,value:"BUSINESS"},
    { title: "Defence" ,value:"DEFENCE"},
    { title: "Not-working" ,value:"NOTWORKING"},
    { title: "Other" ,value:"OTHER"},
    { title: "Not Specified" ,value:"NOT_SPECIFIED"},
  ];
  export const employeeption = [
    { title: "IT" },
    { title: "Marketing" },
    { title: "Bank" },
    { title: "other" },
  ];

  export const familyType = [
    { title: "Joint Family" ,value:'JOINT_FAMILY'},
    { title: "Nuclear Family" ,value:'NUCLEAR_FAMILY'}
  ];


export const familyStatus=[
  { title: "Middle Class" ,value:'MIDDLE_CLASS'},
  { title: "Upper Middle Class" ,value:'UPPER_MIDDLE_CLASS'},
  { title: "Rich Affluent" ,value:'RICH_AFFLUENT'},
]

export const education_=[
  "B.E / B.Tech",
  "M.E / M.Tech",
  "M.S Engineering",
  "B.Eng (Hons)",
  "M.Eng (Hons)",
  "Engineering Diploma",
  "AE",
  "AET",
  "B.A",
  "B.Ed",
  "BJMC",
  "BFA",
  "B.Arch",
  "B.Des",
  "BMM",
  "MFA",
  "M.Ed",
  "M.A",
  "MSW",
  "MJMC",
  "M.Arch",
  "M.Des",
  "BA (Hons)",
  "B.Arch (Hons)",
  "DFA",
  "D.Ed",
  "D.Arch",
  "AA",
  "AFA",
  "B.Com",
  "CA / CPA",
  "CFA",
  "CS",
  "BSc / BFin",
  "M.Com",
  "MSc / MFin / MS",
  "BCom (Hons)",
  "PGD Finance",
  "BCA",
  "B.IT",
  "BCS",
  "BA Computer Science",
  "MCA",
  "PGDCA",
  "IT Diploma",
  "ADIT",
  "B.Sc",
  "M.Sc",
  "BSc (Hons)",
  "DipSc",
  "AS",
  "AAS",
  "MBBS",
  "BDS",
  "BPT",
  "BAMS",
  "BHMS",
  "B.Pharma",
  "BVSc",
  "BSN / BScN",
  "MDS",
  "MCh",
  "M.D",
  "M.S Medicine",
  "MPT",
  "DM",
  "M.Pharma",
  "MVSc",
  "MMed",
  "PGD Medicine",
  "ADN",
  "BBA",
  "BHM",
  "BBM",
  "MBA",
  "PGDM",
  "ABA",
  "ADBus",
  "BL / LLB",
  "ML / LLM",
  "LLB (Hons)",
  "ALA",
  "Ph.D",
  "M.Phil",
  "Bachelor",
  "Master",
  "Diploma",
  "Honours",
  "Doctorate",
  "Associate",
  "High school",
  "Less than high school",
]

export const hobbies=[
    "Acting",
  'Animal breeding',
  'Art / Handicraft',
  'Astrology / Palmistry / Numerology',
  'Astronomy',
  'Bird watching',
  'Collectibles',
  'Cooking',
  'Dancing',
  'DIY(do it yourself) projects',
  'Film-making','Fishing',
  'Gardening / Landscaping',
  'Graphology',
  'Ham radio',
  'Home / Interior decoration',
   'Hunting',  
   'Model building',
   'Painting / Drawing',
   'Photography',
   'Playing musical instruments',
   'Singing',
   'Solving Crosswords', 'Puzzles'
  // Will tell you later
]


 export const gotram=[
  "Aatharvas",
  "Agasthi",
  "Ahabhunasa",
  "Airan",
  "Alampayana",
  "Angiras",
  "Arrishinimi",
  "Athreyasya/ Athreyasa",
  "Atri",
  "Attarishi",
  "Aukshanas",
  "Aushanas",
  "Babrahvya",
  "Badarayana",
  "Baijvayas",
  "Bansal",
  "Bashan",
  "Bhandal",
  "Bharadwaj",
  "Bhargava / Bhargav",
  "Bhasyan",
  "Bhrigu",
  "Bindal",
  "Birthare",
  "Bodhaaynas",
  "Chandratri",
  "Chikithasa",
  "Chyavanasa",
  "Daksa",
  "Dalabhya",
  "Darbhas",
  "Devrata",
  "Dhananjaya",
  "Dhanvantri",
  "Dhara Gautam",
  "Dharan",
  "Dharanas",
  "Dixit",
  "Duttatreyas",
  "Galiva",
  "Ganganas",
  "Gangyanas",
  "Gardhmukh Sandilya",
  "Garg",
  "Garga / Gargya",
  "Gargya Sainasa",
  "Gautam / Gouthama",
  "Ghrit Kaushika",
  "Gowri Veetham",
  "Goyal",
  "Goyan",
  "Haritasya / Harithasa / Haritha",
  "Jaiminiyas",
  "Jamadagni",
  "Jatukarna",
  "Jindal",
  "Kaakavas",
  "Kabi",
  "Kalabouddasa",
  "Kalpangeerasa",
  "Kamakayana Vishwamitra",
  "Kamsa",
  "Kanav",
  "Kansal",
  "Kanva",
  "Kapi",
  "Kapila",
  "Kapinjal",
  "Kapishthalas",
  "Kaplish Baradwaj",
  "Kashish",
  "Kashyapa / Kaashyapa",
  "Katyayan / Katyan",
  "Kaundinya / Koundanya / Kaundilya",
  "Kaunsa",
  "Kaushal",
  "Kaushika / Kaushik / Kausikasa",
  "Keshoryas",
  "Koushika Visvamitrasa",
  "Krishnatrey",
  "Kucchal",
  "Kusa",
  "Kutsa / Kutsas / Kutsasa",
  "Laakshmanas",
  "Laugakshi",
  "Lavania",
  "Lodwan",
  "Lohit",
  "Lokaakhyas",
  "Lomasha",
  "Madelia",
  "Madhukul",
  "Maitraya",
  "Manava",
  "Mandavya",
  "Mangal",
  "Marica",
  "Markendeya",
  "Maudlas",
  "Maunas",
  "Mihir",
  "Mittal",
  "Moudgalya",
  "Mouna Bhargava",
  "Munish",
  "Mythravaruna",
  "Naagal",
  "Nagasya",
  "Naidrupa Kashyapa",
  "Narayanas",
  "Nithyandala",
  "Paaniyas",
  "Pachori",
  "Paing",
  "Parashar / Parashara",
  "Parthivasa",
  "Paulastya",
  "Poothamanasa",
  "Pourugutsa",
  "Prachinas",
  "Raghuvanshi",
  "Rajoria",
  "Rathitar",
  "Rohinya",
  "Rohita",
  "Sakalya",
  "Sakhyanasa",
  "Salankayanasa",
  "Sankash",
  "Sankha",
  "Sankrut",
  "Sankyanasa",
  "Savanaka",
  "Savarana / Sabarna / Savarna / Sraborno",
  "Shaalaksha",
  "Shadamarshana / Shatamarshanam",
  "Shakhanas",
  "Shalavatsa",
  "Shandilya / Sandilyasa",
  "Sharkaras",
  "Sharkvas",
  "Shaunak",
  "Shravanesya",
  "Shrimukh  Shandilya",
  "Shukla Atreyas",
  "Sigidha",
  "Singhal",
  "Sri Vatsa / Vatsa / Vats / Vacchas",
  "Srungi Bharadwajasa",
  "Suparnasa",
  "Swathantra Kapisa",
  "Tayal",
  "Tharakayanam",
  "Thingal",
  "Titwal",
  "Tushar",
  "Udbahu",
  "Udhalaka",
  "Uditha Gautham",
  "Udithya",
  "Upamanyu Vasishtasa",
  "Upamanyu",
  "Upathya",
  "Vadoola  / Vadulasa",
  "Vainya",
  "Vardheyasa",
  "Vashishtha",
  "Veethahavya",
  "Vishnordhageerasa",
  "Vishnu Vridhha",
  "Vishwamitra",
  "Yaska",
  "Others",
  "Don't know"]


export const workingAs=[
"Software Developer / Programmer",
"Software Consultant",
"Hardware & Networking professional"

]

  export default {
    familyValbro,familyValsis,
    profileoption,religionoption,
    chidoption,languageoption,
    statusoption,annualoption,gotram,
    familyVal,heightoption,countryoption,
    familyStatus,familyType,workingAs,
    stateoption,cityoption,rassioption,castoption,degreeoption,employoption,employeeption,motherTongue
  }

//   export const hobbies=[
//     {title:"Acting",value:1},
//     {title:'Animal breeding',value:2},
//     {title:'Art / Handicraft',value:3},
//     {title:'Astrology / Palmistry / Numerology',value:},
//     {title:'Astronomy',value:},
//     {title:'Bird watching',value:},
//     {title:'Collectibles',value:},
//     {title:'Cooking',value:},
//     {title:'Dancing',value:},
//     {title:'DIY(do it yourself) projects',value:},
//     {title:'Film-making','Fishing',value:},
//     {title:'Gardening / Landscaping',value:},
//     {title:'Graphology',value:},
//     {title:'Ham radio',value:},
//     {title:'Home / Interior decoration',value:},
//     {title:'Hunting',  value:},
//     {title:'Model building',value:},
//     {title:'Painting / Drawing',value:},
//     {title:'Photography',value:},
//     {title:'Playing musical instruments',value:},
//     {title:'Singing',value:},
//     {title:'Solving Crosswords', value:},
//     {title:'Puzzles'value:},
//   // Will tell you later
// ]





   
