import gql from 'graphql-tag';
export default gql`query GetSuggestion($id:String!){
  getSuggestion(id:$id){
      items{
        id
        fname
        gender
        interest {
          id
          interest
          tablename
          status
        }
        height
        weight
        profilePic
        maritalStatus
        profileCreatedFor
        username
        religion
        caste
        motherTongue
        aboutMe
        education{
            highestEducation
            colg_institute
            eduDetails
            employedIn
            occupation
            occuDetails
            annualIncome
        }
        request{
            tablename
            id
            status
        }
        location{
            country
            state
            city
            citizenship
        }
        partnerConnectStatus{
            id
            tablename
            status
    }
    connectStatusForMe{
            id
            tablename
            status
    }
      }
  }
  }`
  ;